#Debian Stretch
FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y build-essential cmake libgsl-dev libboost-all-dev libfftw3-dev python3 python3-dev python3-numpy python3-matplotlib libtiff5-dev qt5-default libqt5designercomponents5 qttools5-dev libqt5svg5-dev

ADD ./src /src
WORKDIR /